$SnapinCheck = get-pssnapin -Name VMware.VimAutomation.Core -ErrorAction SilentlyContinue

if ($SnapinCheck -eq $NULL)
{
 write-host ("Adding VMware Snapin...")
 add-pssnapin VMware.VimAutomation.Core
 write-host ("Complete")
}

connect-viserver CRIFVC.criflending.com -user cdupree -password L1thiumCmwys5%

Move-VM -VM	1STNIAGARAAPP02	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	AZSTATEAPP02	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	BROADWAYAPP01	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	CENTRALBNKAPP02	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	COMERICAAPP01	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	COMERICAAPP02	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	COMERICAAPP03	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	COMERICAAPP03x	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	DESERTAPP03	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	DESERTAPP04	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	FCCUAPP03	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	HCFCUAPP01	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	HCFCUAPP02	-datastore	LUN_612-FC_LCC_APP5A
Move-VM -VM	IDAHOCCUAPP01	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	LLBAPP01	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	LLBAPP02	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	MARINEFCUAPP01	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	METROBANKAPP1	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	MFSBAPP01	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	MFSBAPP02	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	MFSBDOC	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	MFSBRISK	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	NHSBAPP01	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	NHSBAPP02	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	NORTHEASTAPP01	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	SACRAMENTORISK	-datastore	LUN_613-FC_LCC_APP5B
Move-VM -VM	SANDIADOC	-datastore	LUN_614-FC_LCC_APP5C
Move-VM -VM	SEAWESTRISK	-datastore	LUN_614-FC_LCC_APP5C
Move-VM -VM	SEVEN17DOC	-datastore	LUN_614-FC_LCC_APP5C
Move-VM -VM	STMARYSDOC	-datastore	LUN_614-FC_LCC_APP5C
Move-VM -VM	TRICOFCURISK	-datastore	LUN_614-FC_LCC_APP5C
Move-VM -VM	UBANDTAPP02	-datastore	LUN_614-FC_LCC_APP5C
Move-VM -VM	UBANDTAPP03	-datastore	LUN_614-FC_LCC_APP5C
Move-VM -VM	UBANDTDOC1	-datastore	LUN_614-FC_LCC_APP5C
Move-VM -VM	USALLIANCEDOC	-datastore	LUN_614-FC_LCC_APP5C
Move-VM -VM	USFIRSTFCUDOC	-datastore	LUN_614-FC_LCC_APP5C
Move-VM -VM	USFIRSTFCURISK	-datastore	LUN_614-FC_LCC_APP5C
Move-VM -VM	UVACCUDOC	-datastore	LUN_614-FC_LCC_APP5C
