$SnapinCheck = get-pssnapin -Name VMware.VimAutomation.Core -ErrorAction SilentlyContinue

if ($SnapinCheck -eq $NULL)
{
 write-host ("Adding VMware Snapin...")
 add-pssnapin VMware.VimAutomation.Core
 write-host ("Complete")
}

connect-viserver CRIFVC.criflending.com -user cdupree -password L1thiumCmwys5%

Move-VM -VM ANBTXDOC -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM BMWAPP07 -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM CACOASTCUAPP02 -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM CACOASTCUDOC -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM CENTRALBANKDOC -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM CNTRLBANKHAPP1 -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM CNTRLBANKHAPP2 -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM COMERICADOC -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM COMMERCELCCDOC -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM DESERTDOC2 -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM DESERTPRTSVR -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM FARMLCBAPP02 -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM FNBALEX -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM FTCAMPBELLDOC -datastore LUN_609-FC_LCC_APP4A
Move-VM -VM HCFCUDOC -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM HCFCURISK -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM HIBERNIAPRTSVR1 -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM HOMEFEDDOC2 -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM LACAPDOC -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM LBSFCURISK -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM LEXINGTONDOC1 -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM LLBDOC -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM LLBRISK -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM NASSAUAPP01 -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM NASSAUDOC -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM NASSAURISK -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM PROVIDENTAPP01 -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM PSCUAPP01 -datastore LUN_610-FC_LCC_APP4B
Move-VM -VM PSCUAPP02 -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM RIVERCITYDOC -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM ROCKLANDAPP01 -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM SANCUAPP02 -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM SANCUAPP04 -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM SANDYSPRAPP01 -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM SANDYSPRAPP02 -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM SEAWESTAPP01 -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM SEAWESTAPP02 -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM SIMMONSAPP01 -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM SIMMONSAPP02 -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM TCUNHAPP01 -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM TEACHERSAPP01 -datastore LUN_611-FC_LCC_APP4C
Move-VM -VM USECUDOC -datastore LUN_611-FC_LCC_APP4C
