$SnapinCheck = get-pssnapin -Name VMware.VimAutomation.Core -ErrorAction SilentlyContinue

if ($SnapinCheck -eq $NULL)
{
 write-host ("Adding VMware Snapin...")
 add-pssnapin VMware.VimAutomation.Core
 write-host ("Complete")
}

connect-viserver CRIFVC.criflending.com -user cdupree -password L1thiumCmwys5%

Move-VM -VM AFFINITYAPP01 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM AFFINITYAPP02 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM AMALGAMAPP01 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM AMALGAMAPP02 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM AMFIRSTAPP01 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM CIBMARINEAPP01 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM CIBMARINEAPP02 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM ENCOREAPP01 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM ENCOREAPP02 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM FARMLCBAPP01 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM FILOAPP01 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM FILOAPP02 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM HANCOCKAPP01 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM HANCOCKAPP02 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM LBSFCUAPP02 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM MERCANTILEAPP01 -datastore LUN_606-FC_LCC_APP3A
Move-VM -VM MERCANTILEAPP02 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM METROBANKAPP01 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM MONOCAPP01 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM MONOCAPP02 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM MONTEREYAPP01 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM MONTEREYAPP02 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM NORTHEASTAPP02 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM NUVISIONAPP01 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM NUVISIONAPP02 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM PEOPLESCUAPP01 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM PEOPLESCUAPP02 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM PROVIDENTAPP02 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM PSCUAPP03 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM RIVERCITYAPP01 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM RIVERCITYAPP02 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM SACRAMENTOAPP01 -datastore LUN_607-FC_LCC_APP3B
Move-VM -VM SACRAMENTOAPP02 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM SANCUAPP01 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM SANCUAPP03 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM SEVEN17APP01 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM SEVEN17APP02 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM SEVEN17APP03 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM TCUNHAPP02 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM TEACHERSAPP02 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM TRICOAPP01 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM TRICOAPP02 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM UBANDTAPP04 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM UNBNKVAAPP01 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM UNBNKVAAPP02 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM USALLIANCEAPP01 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM USALLIANCEAPP02 -datastore LUN_608-FC_LCC_APP3C
Move-VM -VM WORKERSCUAPP01 -datastore LUN_608-FC_LCC_APP3C
