$SnapinCheck = get-pssnapin -Name VMware.VimAutomation.Core -ErrorAction SilentlyContinue

if ($SnapinCheck -eq $NULL)
{
 write-host ("Adding VMware Snapin...")
 add-pssnapin VMware.VimAutomation.Core
 write-host ("Complete")
}

connect-viserver CRIFVC.criflending.com -user cdupree -password L1thiumCmwys5%

Move-VM -VM 1STNIAGARAAPP01 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM AMFIRSTAPP02 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM ANBTXLCBAPP01 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM ARSENALCUAPP01 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM ARSENALCUAPP02 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM BMWAPP04 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM BOSAPP01 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM BOSAPP02 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM BOSAPP03 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM CAMPUSUSAAPP01 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM CAMPUSUSAAPP02 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM CAMPUSUSAAPP03 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM CARDINALAPP01 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM CARDINALAPP02 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM COMAMERICAAPP01 -datastore LUN_603-FC_LCC_APP2A
Move-VM -VM CTCUAPP01 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM CUACAPP01 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM CUACAPP02 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM FCBAPP01 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM FCBAPP02 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM FCCUAPP02 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM FIRSTCOMCUAPP02 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM FTCAMPBELLAPP01 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM FTCAMPBELLAPP02 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM HOMEFEDAPP01 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM IDAHOCCUAPP02 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM LACAPAPP01 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM LACAPAPP02 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM LANDMARKAPP01 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM LANDMARKAPP02 -datastore LUN_604-FC_LCC_APP2B
Move-VM -VM LEXINGTONAPP01 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM MARINEFCUAPP02 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM MDWFCUAPP01 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM MDWFCUAPP02 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM MDWFCUAPP03 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM STMARYSAPP01 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM STMARYSAPP02 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM TINKERFCUAPP01 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM TINKERFCUAPP02 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM TRUSTMARKAPP01 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM TRUSTMARKAPP02 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM UBWVAPP02 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM UVACCUAPP01 -datastore LUN_605-FC_LCC_APP2C
Move-VM -VM UVACCUAPP02 -datastore LUN_605-FC_LCC_APP2C
