name: DeployToLab

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Update Repo
        shell: bash
        run: |
          git -C /home/runner/git/PowerShell pull origin master

      - name: Install-DupreeFunctions-Local
        shell: pwsh
        run: |
          $DfVersion = (Import-PowerShellDataFile /home/runner/git/PowerShell/DupreeFunctions/DupreeFunctions.psd1).ModuleVersion
          $DestPath = "/usr/local/share/powershell/Modules/DupreeFunctions/$DfVersion"
          New-Item -Path $DestPath -ItemType Directory -Force | Out-Null
          Copy-Item -Path /home/runner/git/PowerShell/DupreeFunctions/* -Destination $DestPath -Recurse -Force

      - name: Update-DfLabBoxes
        shell: pwsh
        run: |
          Import-Module DupreeFunctions
          Update-DfLabBoxes
