# This is a basic workflow to help you get started with Actions

name: VersionUpdate

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "master" branch
  pull_request:
    types: [closed]
    branches:
      - version

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Update repository on JAX-TASK001
      - name: Update Repo
        shell: cmd
        run: |
          git -C C:\git\PowerShell pull origin version

      - name: Update Version
        shell: PowerShell
        run: |
          Update-DfModuleVersion

      # Publish DupreeFunctions to PSG
      - name: Update Branch
        shell: cmd
        run: |
          git add C:\actions-runner\_work\PowerShell\PowerShell\DupreeFunctions\DupreeFunctions.psd1
          git commit
          git push